# Generated by Django 5.1.5 on 2025-05-09 21:26

import dirtyfields.dirtyfields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('link', models.URLField(blank=True, help_text='Link a donde redirige el anuncio', null=True)),
                ('position', models.CharField(choices=[('left', 'Izquierda'), ('right', 'Derecha'), ('inline', 'Dentro del contenido'), ('bottom', 'Final del contenido')], default='right', help_text='Ubicación del anuncio en la página', max_length=10)),
                ('custom_script', models.TextField(blank=True, help_text='Código HTML o script del anuncio (tendrá prioridad sobre la imagen si se define)', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='anuncios/')),
                ('titulo', models.CharField(blank=True, help_text='Opcional: Título o descripción breve del anuncio.', max_length=255, null=True)),
                ('link', models.URLField(blank=True, help_text='A dónde redirige el anuncio al hacer clic sobre la imagen', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('vertical_left', 'Vertical Izquierdo'), ('vertical_right', 'Vertical Derecho'), ('horizontal_after_carousel', 'Horizontal - Después del Carrusel'), ('horizontal_after_main_news', 'Horizontal - Después de Noticias Principal'), ('horizontal_after_podcast', 'Horizontal - Después del Podcast'), ('horizontal_after_programs', 'Horizontal - Después de Programas')], max_length=30, verbose_name='Posición')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Número que define el orden de aparición (de menor a mayor)', verbose_name='Orden de aparición')),
                ('script', models.TextField(help_text='Copia y pega el código HTML del banner generado', verbose_name='Código del Banner')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el banner se muestra en la página', verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Banner Publicitario',
                'verbose_name_plural': 'Banners Publicitarios',
                'ordering': ['position', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='CarouselNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='carousel_news/')),
                ('pie_de_foto', models.CharField(blank=True, help_text='Texto descriptivo o pie de foto de la imagen', max_length=255, verbose_name='Pie de foto')),
                ('credit', models.CharField(blank=True, help_text='Autor o fuente de la imagen', max_length=255, verbose_name='Crédito de la imagen')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='MainNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(blank=True, help_text='Sube un video (formato mp4 recomendado)', null=True, upload_to='main_news/videos/')),
                ('video_link', models.URLField(blank=True, help_text='O ingresa un link al video (por ejemplo, YouTube embed)', null=True)),
                ('image', models.ImageField(blank=True, help_text='Usa esta imagen si no se proporciona un video', null=True, upload_to='main_news/images/')),
                ('pie_de_foto', models.CharField(blank=True, help_text='Texto descriptivo o pie de foto ', max_length=255, verbose_name='Pie de foto')),
                ('credit', models.CharField(blank=True, help_text='Autor o fuente de la imagen', max_length=255, verbose_name='Crédito de la imagen')),
                ('author', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('short_description', models.TextField(help_text='Descripción corta de la noticia')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Título opcional para el video', max_length=255, null=True)),
                ('video_file', models.FileField(blank=True, help_text='Sube un archivo de video (mp4 recomendado)', null=True, upload_to='videos/')),
                ('video_link', models.URLField(blank=True, help_text='O ingresa un link al video (por ejemplo, URL de YouTube embed)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PodcastSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='podcasts_covers/')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Sección de Podcast',
                'verbose_name_plural': 'Secciones de Podcast',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('host', models.CharField(blank=True, max_length=200, null=True)),
                ('duracion', models.CharField(blank=True, help_text='Ejemplo: 4:47', max_length=10, null=True)),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('peso_archivo', models.CharField(blank=True, help_text='Tamaño del audio (ej: 3.5 MB)', max_length=20, null=True)),
                ('url_reproducir', models.URLField(blank=True, help_text='URL externa de reproducción (opcional)', null=True)),
                ('audio', models.FileField(blank=True, help_text='Sube un archivo de audio (.mp3, .wav, .ogg, .m4a)', null=True, upload_to='programas/audios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])])),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('programa', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='programacion_imagenes/')),
                ('hora', models.TimeField()),
                ('zona_horaria_usuario', models.CharField(choices=[('America/Mexico_City', 'Mexico'), ('America/Bogota', 'Bogota'), ('America/Argentina/Buenos_Aires', 'Argentina'), ('America/New_York', 'EEUU')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PublicidadContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('empresa', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TwitchSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('twitch_channel', models.CharField(default='contactototal', max_length=100, verbose_name='Canal de Twitch')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Horario de Twitch',
                'verbose_name_plural': 'Horarios de Twitch',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EdicionRevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='revistas/portadas/')),
                ('fecha_publicacion', models.DateField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], db_index=True, default='draft', max_length=10)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, unique=True)),
                ('pdf', models.FileField(blank=True, help_text='Si sólo subes este PDF, no habrá detalle de artículos', null=True, upload_to='revistas/pdf/')),
            ],
            options={
                'ordering': ['-fecha_publicacion', '-id'],
                'indexes': [models.Index(fields=['slug'], name='stationRadi_slug_7190f2_idx'), models.Index(fields=['status', 'fecha_publicacion'], name='stationRadi_status_aae8df_idx')],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seccion', models.CharField(choices=[('actualidad_local', 'Actualidad local'), ('actualidad_nacional', 'Actualidad nacional'), ('aniversario', 'Aniversario'), ('buena_vida', 'Buena vida'), ('calendario_de_eventos', 'Calendario de eventos'), ('camino_al_exito', 'Camino al éxito'), ('comunidad', 'Comunidad'), ('casos_de_familia', 'Casos de familia'), ('cuide_su_salud', 'Cuide su salud'), ('de_compras', 'De compras'), ('de_nuestros_consulados', 'De nuestros consulados'), ('de_su_bolsillo', 'De su bolsillo'), ('de_su_ronco_pecho', 'De su ronco pecho'), ('destacado', 'Destacado'), ('destinos', 'Destinos'), ('detras_de_camaras', 'Detrás de cámaras'), ('dia_del_padre', 'Día del padre'), ('dia_de_la_madre', 'Día de la madre'), ('echandole_ganas', 'Echándole ganas'), ('editorial', 'Editorial'), ('elecciones', 'Elecciones'), ('en_la_jugada', 'En la jugada'), ('en_la_mira', 'En la mira'), ('en_pantalla', 'En pantalla'), ('enterate', 'Entérate'), ('especial', 'Especial'), ('exclusivo', 'Exclusivo'), ('estilo_y_belleza', 'Estilo y belleza'), ('estrenos', 'Estrenos'), ('famosos_de_aqui_y_alla', 'Famosos de aquí y allá'), ('gente_en_contacto_total', 'Gente en Contacto total'), ('inmigracion_al_dia', 'Inmigración al día'), ('herencia_hispana', 'Herencia Hispana'), ('mundo_empresarial', 'Mundo empresarial'), ('muy_personal', 'Muy personal'), ('nuestra_musica', 'Nuestra música'), ('orgullo_hispano', 'Orgullo hispano'), ('panorama_local', 'Panorama local'), ('panorama_mundial', 'Panorama mundial'), ('panorama_nacional', 'Panorama nacional'), ('pantalla_chica', 'Pantalla chica'), ('pantalla_grande', 'Pantalla grande'), ('para_chuparse_los_dedos', 'Para chuparse los dedos'), ('primer_plano', 'Primer plano'), ('punto_de_vista', 'Punto de vista'), ('que_no_le_pase_a_usted', 'Que no le pase a usted'), ('salud_y_belleza', 'Salud y belleza'), ('si_se_puede', 'Sí se puede'), ('streaming', 'Streaming'), ('talento_local', 'Talento local'), ('vida_de_mascota', 'Vida de mascota'), ('vida_de_pareja', 'Vida de pareja'), ('vida_segura', 'Vida segura'), ('voces', 'Voces'), ('yo_recomiendo', 'Yo recomiendo'), ('zona_digital', 'Zona digital')], default='actualidad_local', max_length=50, verbose_name='Sección')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, unique=True)),
                ('portada', models.ImageField(upload_to='revistas/articulos/')),
                ('portada_pie_de_foto', models.CharField(blank=True, help_text='Pie de foto de la portada', max_length=255)),
                ('portada_credito', models.CharField(blank=True, help_text='Crédito de la imagen de portada', max_length=255)),
                ('descripcion_corta', models.CharField(help_text='Resumen breve', max_length=255)),
                ('contenido', models.TextField(help_text='Descripción completa')),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_publicado', models.DateField(auto_now_add=True, db_index=True)),
                ('es_principal', models.BooleanField(db_index=True, default=False, help_text='Marca este artículo como principal')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en la lista')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], db_index=True, default='draft', max_length=10)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Número de vistas')),
                ('external_url', models.URLField(blank=True, help_text='URL externa relacionada con este artículo', max_length=500, null=True)),
                ('edicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='stationRadio.edicionrevista')),
                ('tags', models.ManyToManyField(blank=True, related_name='articulos', to='stationRadio.tag')),
            ],
            options={
                'ordering': ['-es_principal', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ImagenArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='revistas/articulos/imagenes/')),
                ('contenido', models.TextField(blank=True, help_text='Texto o descripción que acompañará a esta imagen')),
                ('pie_de_foto', models.CharField(blank=True, help_text='Texto descriptivo o pie de foto', max_length=255)),
                ('credito', models.CharField(blank=True, help_text='Nombre del autor o fuente', max_length=255)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el contenido')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='stationRadio.articulo')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PodcastAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='podcasts_audio/')),
                ('audio_link', models.URLField(blank=True, help_text='Enlace embed de YouTube, por ejemplo', null=True)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('podcast_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='stationRadio.podcastsection')),
            ],
            options={
                'verbose_name': 'Audio de Podcast',
                'verbose_name_plural': 'Audios de Podcast',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='PodcastVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_link', models.URLField(blank=True, help_text='Enlace embed de YouTube, por ejemplo', null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='podcasts_video_covers/')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('podcast_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='stationRadio.podcastsection')),
            ],
            options={
                'verbose_name': 'Video de Podcast',
                'verbose_name_plural': 'Videos de Podcast',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['slug'], name='stationRadi_slug_f8698d_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['status', 'es_principal'], name='stationRadi_status_ef318f_idx'),
        ),
        migrations.AddConstraint(
            model_name='articulo',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('edicion',), name='one_principal_per_edicion'),
        ),
    ]
