# Generated by Django 5.1.5 on 2025-05-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainnews',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
