# Generated by Django 5.1.5 on 2025-05-24 05:02

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0002_alter_mainnews_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacion',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='programacion',
            name='hora',
        ),
        migrations.AddField(
            model_name='programacion',
            name='dias_semana',
            field=models.JSONField(default=list, help_text="Lista de días de emisión (usar claves: 'mon','tue',...,'sun')", verbose_name='Días de la semana'),
        ),
        migrations.AddField(
            model_name='programacion',
            name='hora_fin',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Hora local de finalización de la transmisión', verbose_name='Hora de fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programacion',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2025, 5, 24, 5, 2, 48, 928220, tzinfo=datetime.timezone.utc), help_text='Hora local de inicio de la transmisión', verbose_name='Hora de inicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programacion',
            name='zona_horaria_usuario',
            field=models.CharField(choices=[('America/Mexico_City', 'México'), ('America/Bogota', 'Bogotá'), ('America/Argentina/Buenos_Aires', 'Argentina'), ('America/New_York', 'EEUU')], default='America/Bogota', max_length=50, verbose_name='Zona horaria base'),
        ),
    ]
