# Generated by Django 5.1.5 on 2025-03-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0002_programa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
                ('programa', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='programacion_imagenes/')),
                ('hora', models.CharField(max_length=5)),
                ('zona_horaria', models.CharField(choices=[('America/Mexico_City', 'Mexico'), ('America/Bogota', 'Bogota'), ('America/Argentina/Buenos_Aires', 'Argentina'), ('Chile', 'Chile')], max_length=50)),
            ],
        ),
    ]
