# Generated by Django 5.2.5 on 2025-08-30 16:02
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0003_remove_programacion_dia_remove_programacion_hora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ubicación de página',
                'verbose_name_plural': 'Ubicaciones de página',
            },
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='show_in_all',
            field=models.BooleanField(default=True, help_text='Si está activo, el anuncio se muestra en todas las vistas.'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='custom_script',
            field=models.TextField(blank=True, help_text='HTML/script del anuncio (tiene prioridad sobre la imagen)', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='position',
            field=models.CharField(choices=[('left', 'Izquierda'), ('right', 'Derecha'), ('inline', 'Dentro del contenido'), ('bottom', 'Final del contenido')], db_index=True, default='right', help_text='Ubicación del anuncio en la página', max_length=10),
        ),
        migrations.AddField(
            model_name='announcement',
            name='placements',
            field=models.ManyToManyField(blank=True, help_text="Si 'Todas las páginas' está desmarcado, selecciona en qué vistas aparece.", related_name='announcements', to='stationRadio.pageplacement'),
        ),
    ]
