# Generated by Django 5.1.5 on 2025-03-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0005_alter_programacion_zona_horaria_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion',
            name='dia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='programacion',
            name='zona_horaria_usuario',
            field=models.CharField(choices=[('America/Mexico_City', 'Mexico'), ('America/Bogota', 'Bogota'), ('America/Argentina/Buenos_Aires', 'Argentina'), ('Chile/Continental', 'Chile'), ('America/New_York', 'EEUU')], max_length=50),
        ),
    ]
