# Generated by Django 5.2.5 on 2025-08-30 HH:MM
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0005_seed_page_placements'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image_desktop',
            field=models.ImageField(upload_to='announcements/desktop/', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image_tablet',
            field=models.ImageField(upload_to='announcements/tablet/', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image_mobile',
            field=models.ImageField(upload_to='announcements/mobile/', blank=True, null=True),
        ),
    ]
