# Generated by Django 5.1.5 on 2025-03-29 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0006_alter_programacion_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion',
            name='zona_horaria_usuario',
            field=models.CharField(choices=[('America/Mexico_City', 'Mexico'), ('America/Bogota', 'Bogota'), ('America/Argentina/Buenos_Aires', 'Argentina'), ('America/New_York', 'EEUU')], max_length=50),
        ),
    ]
