# Generated by Django 5.1.5 on 2025-03-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0008_alter_programacion_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacion',
            name='dia',
            field=models.CharField(max_length=20),
        ),
    ]
