# Generated by Django 5.1.5 on 2025-04-03 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0010_alter_programacion_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdicionRevista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='revistas/')),
                ('fecha_publicacion', models.DateField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MainVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Título opcional para el video', max_length=255, null=True)),
                ('video_file', models.FileField(blank=True, help_text='Sube un archivo de video (mp4 recomendado)', null=True, upload_to='videos/')),
                ('video_link', models.URLField(blank=True, help_text='O ingresa un link al video (por ejemplo, URL de YouTube embed)', null=True)),
            ],
        ),
    ]
