# Generated by Django 5.1.5 on 2025-04-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0011_edicionrevista_mainvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='anuncios/')),
                ('titulo', models.CharField(blank=True, help_text='Opcional: Título o descripción breve del anuncio.', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarouselNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='carousel_news/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(blank=True, help_text='Sube un video (formato mp4 recomendado)', null=True, upload_to='main_news/videos/')),
                ('video_link', models.URLField(blank=True, help_text='O ingresa un link al video (por ejemplo, YouTube embed)', null=True)),
                ('image', models.ImageField(blank=True, help_text='Usa esta imagen si no se proporciona un video', null=True, upload_to='main_news/images/')),
                ('author', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('short_description', models.TextField(help_text='Descripción corta de la noticia')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
