# Generated by Django 5.1.5 on 2025-04-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0013_alter_edicionrevista_fecha_publicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('link', models.URLField(blank=True, help_text='Link a donde redirige el anuncio', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='podcast',
            name='podcast_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('mixed', 'Mixto')], default='audio', max_length=10),
        ),
        migrations.AddField(
            model_name='podcast',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='video_link',
            field=models.URLField(blank=True, help_text='Enlace para el video (embed de YouTube, por ejemplo)', null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='podcasts_audio/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='podcasts_covers/'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
