# Generated by Django 5.1.5 on 2025-04-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0014_announcement_podcast_podcast_type_podcast_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
