# Generated by Django 5.1.5 on 2025-04-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0015_alter_podcast_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicionrevista',
            name='pdf',
            field=models.FileField(blank=True, help_text='Sube la revista en formato PDF', null=True, upload_to='revistas/pdf/'),
        ),
    ]
