# Generated by Django 5.1.5 on 2025-04-05 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0016_edicionrevista_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carouselnews',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='duracion',
            field=models.CharField(blank=True, help_text='Ejemplo: 4:47', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='host',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='url_reproducir',
            field=models.URLField(blank=True, null=True),
        ),
    ]
