# Generated by Django 5.1.5 on 2025-04-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0017_programa_fecha_creacion_alter_carouselnews_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='series',
            field=models.CharField(blank=True, help_text='Nombre de la serie o sección', max_length=100, null=True),
        ),
    ]
