# Generated by Django 5.1.5 on 2025-04-05 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0018_podcast_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='podcasts_audio/')),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PodcastSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='podcasts_covers/')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PodcastVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_link', models.URLField(blank=True, help_text='Enlace embed de YouTube, por ejemplo', null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='podcasts_video_covers/')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('podcast_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='stationRadio.podcastsection')),
            ],
        ),
        migrations.DeleteModel(
            name='Podcast',
        ),
        migrations.AddField(
            model_name='podcastaudio',
            name='podcast_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='stationRadio.podcastsection'),
        ),
    ]
