# Generated by Django 5.1.5 on 2025-04-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0019_podcastaudio_podcastsection_podcastvideo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastaudio',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
