# Generated by Django 5.1.5 on 2025-04-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0020_podcastaudio_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastaudio',
            name='featured',
        ),
        migrations.AddField(
            model_name='podcastsection',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
