# Generated by Django 5.1.7 on 2025-04-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0021_remove_podcastaudio_featured_podcastsection_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('vertical_left', 'Vertical Izquierdo'), ('vertical_right', 'Vertical Derecho'), ('horizontal_after_carousel', 'Horizontal - Después del Carrusel'), ('horizontal_after_main_news', 'Horizontal - Después de Noticias Principal'), ('horizontal_after_podcast', 'Horizontal - Después del Podcast'), ('horizontal_after_programs', 'Horizontal - Después de Programas')], max_length=30, verbose_name='Posición')),
                ('orden', models.PositiveIntegerField(default=1, help_text='Número que define el orden de aparición (de menor a mayor)', verbose_name='Orden de aparición')),
                ('script', models.TextField(help_text='Copia y pega el código HTML del banner generado', verbose_name='Código del Banner')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el banner se muestra en la página', verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Banner Publicitario',
                'verbose_name_plural': 'Banners Publicitarios',
                'ordering': ['position', 'orden'],
            },
        ),
    ]
