# Generated by Django 5.1.5 on 2025-04-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0022_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('vertical_left', 'Vertical Izquierdo'), ('vertical_right', 'Vertical Derecho'), ('horizontal_after_carousel', 'Horizontal - Después del Carrusel'), ('horizontal_after_main_news', 'Horizontal - Después de Noticias Principal'), ('horizontal_after_podcast', 'Horizontal - Después del Podcast'), ('horizontal_after_programs', 'Horizontal - Después de Programas')], max_length=30, verbose_name='Posición'),
        ),
    ]
