# Generated by Django 5.1.5 on 2025-04-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0022_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicidadContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=150)),
                ('empresa', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
