# Generated by Django 5.1.5 on 2025-04-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0023_publicidadcontacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='custom_script',
            field=models.TextField(blank=True, help_text='Código HTML o script del anuncio (tendrá prioridad sobre la imagen si se define)', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='position',
            field=models.CharField(choices=[('left', 'Izquierda'), ('right', 'Derecha'), ('inline', 'Dentro del contenido'), ('bottom', 'Final del contenido')], default='right', help_text='Ubicación del anuncio en la página', max_length=10),
        ),
    ]
