# Generated by Django 5.1.5 on 2025-04-16 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0024_announcement_custom_script_announcement_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='programa',
            name='audio',
            field=models.FileField(blank=True, help_text='Sube un archivo de audio (.mp3, .wav, .ogg, .m4a)', null=True, upload_to='programas/audios/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a'])]),
        ),
        migrations.AlterField(
            model_name='programa',
            name='url_reproducir',
            field=models.URLField(blank=True, help_text='URL externa de reproducción (opcional)', null=True),
        ),
    ]
