# Generated by Django 5.1.5 on 2025-04-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0025_contactmessage_programa_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastaudio',
            name='audio_link',
            field=models.URLField(blank=True, help_text='Enlace embed de YouTube, por ejemplo', null=True),
        ),
        migrations.AlterField(
            model_name='podcastaudio',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='podcasts_audio/'),
        ),
    ]
