# Generated by Django 5.1.5 on 2025-04-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0026_podcastaudio_audio_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastaudio',
            name='audio_file',
            field=models.FileField(upload_to='podcasts_audio/'),
        ),
    ]
