# Generated by Django 5.1.5 on 2025-04-25 05:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0027_alter_podcastaudio_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=200, unique=True)),
                ('portada', models.ImageField(upload_to='revistas/articulos/')),
                ('descripcion_corta', models.CharField(help_text='Resumen breve', max_length=255)),
                ('contenido', models.TextField(help_text='Descripción completa')),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_publicado', models.DateField(auto_now_add=True, db_index=True)),
                ('es_principal', models.BooleanField(db_index=True, default=False, help_text='Marca este artículo como principal')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden en la lista')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], db_index=True, default='draft', max_length=10)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Número de vistas')),
                ('external_url', models.URLField(blank=True, help_text='URL externa relacionada con este artículo', max_length=500, null=True)),
            ],
            options={
                'ordering': ['-es_principal', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='edicionrevista',
            options={'ordering': ['-fecha_publicacion', '-id']},
        ),
        migrations.RemoveField(
            model_name='edicionrevista',
            name='url',
        ),
        migrations.AddField(
            model_name='edicionrevista',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edicionrevista',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='edicionrevista',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado')], db_index=True, default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='edicionrevista',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='edicionrevista',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='edicionrevista',
            name='imagen',
            field=models.ImageField(upload_to='revistas/portadas/'),
        ),
        migrations.AlterField(
            model_name='edicionrevista',
            name='pdf',
            field=models.FileField(blank=True, help_text='Si sólo subes este PDF, no habrá detalle de artículos', null=True, upload_to='revistas/pdf/'),
        ),
        migrations.AddIndex(
            model_name='edicionrevista',
            index=models.Index(fields=['slug'], name='stationRadi_slug_7190f2_idx'),
        ),
        migrations.AddIndex(
            model_name='edicionrevista',
            index=models.Index(fields=['status', 'fecha_publicacion'], name='stationRadi_status_aae8df_idx'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='edicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='stationRadio.edicionrevista'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articulos', to='stationRadio.tag'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['slug'], name='stationRadi_slug_f8698d_idx'),
        ),
        migrations.AddIndex(
            model_name='articulo',
            index=models.Index(fields=['status', 'es_principal'], name='stationRadi_status_ef318f_idx'),
        ),
        migrations.AddConstraint(
            model_name='articulo',
            constraint=models.UniqueConstraint(condition=models.Q(('es_principal', True)), fields=('edicion',), name='one_principal_per_edicion'),
        ),
    ]
