# Generated by Django 5.1.5 on 2025-04-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0028_articulo_tag_alter_edicionrevista_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='nombre_archivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programa',
            name='peso_archivo',
            field=models.CharField(blank=True, help_text='Tamaño del audio (ej: 3.5 MB)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
