# Generated by Django 5.1.5 on 2025-04-29 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0029_programa_nombre_archivo_programa_peso_archivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='revistas/articulos/imagenes/')),
                ('pie_de_foto', models.CharField(blank=True, help_text='Texto descriptivo o pie de foto', max_length=255)),
                ('credito', models.CharField(blank=True, help_text='Nombre del autor o fuente', max_length=255)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el contenido')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='stationRadio.articulo')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
