# Generated by Django 5.1.5 on 2025-04-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0030_imagenarticulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='portada_credito',
            field=models.CharField(blank=True, help_text='Crédito de la imagen de portada', max_length=255),
        ),
        migrations.AddField(
            model_name='articulo',
            name='portada_pie_de_foto',
            field=models.CharField(blank=True, help_text='Pie de foto de la portada', max_length=255),
        ),
    ]
