# Generated by Django 5.1.5 on 2025-04-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0031_articulo_portada_credito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='seccion',
            field=models.CharField(choices=[('actualidad_local', 'Actualidad local'), ('actualidad_nacional', 'Actualidad nacional'), ('aniversario', 'Aniversario'), ('buena_vida', 'Buena vida'), ('calendario_de_eventos', 'Calendario de eventos'), ('camino_al_exito', 'Camino al éxito'), ('comunidad', 'Comunidad'), ('casos_de_familia', 'Casos de familia'), ('cuide_su_salud', 'Cuide su salud'), ('de_compras', 'De compras'), ('de_nuestros_consulados', 'De nuestros consulados'), ('de_su_bolsillo', 'De su bolsillo'), ('de_su_ronco_pecho', 'De su ronco pecho'), ('destacado', 'Destacado'), ('destinos', 'Destinos'), ('detras_de_camaras', 'Detrás de cámaras'), ('dia_del_padre', 'Día del padre'), ('dia_de_la_madre', 'Día de la madre'), ('echandole_ganas', 'Echándole ganas'), ('editorial', 'Editorial'), ('elecciones', 'Elecciones'), ('en_la_jugada', 'En la jugada'), ('en_la_mira', 'En la mira'), ('en_pantalla', 'En pantalla'), ('enterate', 'Entérate'), ('especial', 'Especial'), ('exclusivo', 'Exclusivo'), ('estilo_y_belleza', 'Estilo y belleza'), ('estrenos', 'Estrenos'), ('famosos_de_aqui_y_alla', 'Famosos de aquí y allá'), ('gente_en_contacto_total', 'Gente en Contacto total'), ('inmigracion_al_dia', 'Inmigración al día'), ('herencia_hispana', 'Herencia Hispana'), ('mundo_empresarial', 'Mundo empresarial'), ('muy_personal', 'Muy personal'), ('nuestra_musica', 'Nuestra música'), ('orgullo_hispano', 'Orgullo hispano'), ('panorama_local', 'Panorama local'), ('panorama_mundial', 'Panorama mundial'), ('panorama_nacional', 'Panorama nacional'), ('pantalla_chica', 'Pantalla chica'), ('pantalla_grande', 'Pantalla grande'), ('para_chuparse_los_dedos', 'Para chuparse los dedos'), ('primer_plano', 'Primer plano'), ('punto_de_vista', 'Punto de vista'), ('que_no_le_pase_a_usted', 'Que no le pase a usted'), ('salud_y_belleza', 'Salud y belleza'), ('si_se_puede', 'Sí se puede'), ('streaming', 'Streaming'), ('talento_local', 'Talento local'), ('vida_de_mascota', 'Vida de mascota'), ('vida_de_pareja', 'Vida de pareja'), ('vida_segura', 'Vida segura'), ('voces', 'Voces'), ('yo_recomiendo', 'Yo recomiendo'), ('zona_digital', 'Zona digital')], default='actualidad_local', max_length=50, verbose_name='Sección'),
        ),
    ]
