# Generated by Django 5.1.5 on 2025-04-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0032_articulo_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselnews',
            name='credit',
            field=models.CharField(blank=True, help_text='Autor o fuente de la imagen', max_length=255, verbose_name='Crédito de la imagen'),
        ),
        migrations.AddField(
            model_name='carouselnews',
            name='pie_de_foto',
            field=models.CharField(blank=True, help_text='Texto descriptivo o pie de foto de la imagen', max_length=255, verbose_name='Pie de foto'),
        ),
        migrations.AddField(
            model_name='mainnews',
            name='credit',
            field=models.CharField(blank=True, help_text='Autor o fuente de la imagen', max_length=255, verbose_name='Crédito de la imagen'),
        ),
        migrations.AddField(
            model_name='mainnews',
            name='pie_de_foto',
            field=models.CharField(blank=True, help_text='Texto descriptivo o pie de foto ', max_length=255, verbose_name='Pie de foto'),
        ),
    ]
