# Generated by Django 5.1.5 on 2025-04-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0033_carouselnews_credit_carouselnews_pie_de_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenarticulo',
            name='contenido',
            field=models.TextField(blank=True, help_text='Texto o descripción que acompañará a esta imagen'),
        ),
    ]
