# Generated by Django 5.1.5 on 2025-05-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0034_imagenarticulo_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('twitch_channel', models.CharField(default='contactototal', max_length=100, verbose_name='Canal de Twitch')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Horario de Twitch',
                'verbose_name_plural': 'Horarios de Twitch',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
