# Generated by Django 5.1.5 on 2025-05-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationRadio', '0035_twitchschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcastaudio',
            options={'ordering': ['-date_created'], 'verbose_name': 'Audio de Podcast', 'verbose_name_plural': 'Audios de Podcast'},
        ),
        migrations.AlterModelOptions(
            name='podcastsection',
            options={'ordering': ['-date_created'], 'verbose_name': 'Sección de Podcast', 'verbose_name_plural': 'Secciones de Podcast'},
        ),
        migrations.AlterModelOptions(
            name='podcastvideo',
            options={'ordering': ['-date_created'], 'verbose_name': 'Video de Podcast', 'verbose_name_plural': 'Videos de Podcast'},
        ),
    ]
